apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp-color
  name: webapp-color
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp-color
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-color
    spec:
      containers:
      - image:  wiktorvip/webapp-color:5
        name: webapp-color
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service-webapp-color
  labels:
    app: lb-service-webapp-color
spec:
  type: LoadBalancer
  ports:
  - port: 9009
    targetPort: 9009
  selector:
    app: webapp-color
